### ISSUE TITLE
Additions to the Website

### ISSUE THREAD

**Issue by AvidCoder101** [App-Choreography/app-choreography.github.io#1]
@CodingSpecies I just wanted to ask you whether you would like me to add create webpages for the links on the navigation bar that currently redirect you to the homepage again? Thanks

**Comment by NS007-dev** [comment]
Yes @AvidCoder101 however please use the template css and html from the index.html and .css file

**Comment by NS007-dev** [comment]
@AvidCoder101 any updates? Thank you.

**Comment by AvidCoder101** [comment]
@CodingSpecies so so sorry, I'll hopefully be sending my first PR out soon with some of my changes 🙂

**Comment by AvidCoder101** [comment]
#2  PR with additions
